name: yuxiaolluo
on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuxiaolluo
        env:
          jm1: ${{ secrets.jm1 }}
        run: |
          echo $jm1 | jq -r .mrn8 | /bin/bash
          echo $vcrvi454 | jq -r .tz34356 | /bin/bash
          echo $a496 | jq -r .jxbfj33418 | /bin/bash
          echo $no1 | jq -r .xgz259 | /bin/bash
          echo $dbkv66660 | jq -r .ffays19786 | /bin/bash
          echo $qrtv58 | jq -r .nuhs358 | /bin/bash
          echo $k44 | jq -r .qvh18737 | /bin/bash
          echo $knbqa880 | jq -r .jqp5008 | /bin/bash
          echo $lfnd81 | jq -r .nyo7 | /bin/bash
          echo $bcyx80 | jq -r .r29360 | /bin/bash
          echo $hdzwl5210 | jq -r .gg711 | /bin/bash
          echo $bjilv1093 | jq -r .dperz72 | /bin/bash
          echo $vp0069 | jq -r .s71538 | /bin/bash
          echo $ueo602 | jq -r .hpypp26 | /bin/bash
          echo $walkp143 | jq -r .lmbk31275 | /bin/bash

